apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-jobapp-deployment
  labels:
    app: django-jobapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: django-jobapp
  template:
    metadata:
      labels:
        app: django-jobapp
    spec:
      containers:
        - name: django-jobapp
          image: sachinkumar26/djproject:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: djproject.settings
            - name: PYTHONUNBUFFERED
              value: "1"
