apiVersion: v1
kind: Service
metadata:
  name: django-jobapp-service
spec:
  type: NodePort
  selector:
    app: django-jobapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
